Repository Enterprise-CMCS/macpro-mako, pull requests merged in 2023-12, with the labels that each got.

#256 feat(OY2-26203): Add OS Action Column
  src/packages/shared-utils/index.ts
  src/packages/shared-utils/package-actions.ts
  src/services/api/handlers/action.ts
  src/services/api/handlers/getPackageActions.ts
  src/services/ui/src/components/Opensearch/Settings/Visibility.tsx
  src/services/ui/src/components/Opensearch/Table/index.tsx
  src/services/ui/src/components/Opensearch/Table/types.ts
  src/services/ui/src/pages/dashboard/Lists/renderCells/index.tsx
  src/services/ui/src/pages/dashboard/Lists/spas/consts.tsx
  src/services/ui/src/pages/dashboard/Lists/spas/index.tsx
  src/services/ui/src/pages/dashboard/Lists/waivers/consts.tsx
  src/services/ui/src/pages/dashboard/Lists/waivers/index.tsx
Labels: enhancement

#265 feat(OY-26537): OS changelog package activity
  src/libs/opensearch-lib.ts
  src/packages/shared-types/opensearch.ts
  src/services/data/handlers/index.ts
  src/services/data/handlers/sink.ts
Labels: enhancement

#274 fix(package-actions): Wrap `RespondToRai` with package action checks
  src/services/ui/src/pages/actions/RespondToRai.tsx
Labels: bug

#275 feat(package-actions): Refactor logic for `getPackageActions`
  src/packages/shared-types/actions.ts
  src/packages/shared-types/authority.ts
  src/packages/shared-types/index.ts
  src/packages/shared-types/planType.ts
  src/packages/shared-types/seatool.ts
  src/packages/shared-utils/index.ts
  src/packages/shared-utils/package-actions.ts
  src/packages/shared-utils/package-actions/getAvailableActions.ts
  src/packages/shared-utils/package-actions/rules.ts
  src/packages/shared-utils/rai-helper.ts
  src/services/api/handlers/action.ts
  src/services/api/handlers/getPackageActions.ts
  src/services/api/handlers/packageActions.ts
  src/services/api/handlers/submit.ts
  src/services/ui/src/api/submissionService.ts
  src/services/ui/src/pages/actions/IssueRai.tsx
  src/services/ui/src/pages/actions/RespondToRai.tsx
  src/services/ui/src/pages/actions/ToggleRaiResponseWithdraw.tsx
  src/services/ui/src/pages/actions/WithdrawPackage.tsx
  src/services/ui/src/pages/actions/WithdrawRai.tsx
  src/services/ui/src/pages/actions/common.tsx
  src/services/ui/src/pages/dashboard/Lists/renderCells/index.tsx
  src/services/ui/src/pages/dashboard/Lists/spas/consts.tsx
  src/services/ui/src/pages/dashboard/Lists/waivers/consts.tsx
  src/services/ui/src/pages/detail/setup/spa.tsx
  src/services/ui/src/pages/form/chip-form.tsx
  src/services/ui/src/pages/form/medicaid-form.tsx
  src/services/ui/src/utils/textHelpers.ts
Labels: refactor

#285 feat(refactor): App Navigator
  src/services/data/handlers/sink.ts
  src/services/ui/src/components/Cards/OptionCard.test.tsx
  src/services/ui/src/components/Cards/OptionCard.tsx
  src/services/ui/src/components/ExportButton/index.tsx
  src/services/ui/src/components/Layout/index.tsx
  src/services/ui/src/components/Opensearch/Filtering/FilterChips.tsx
  src/services/ui/src/components/Opensearch/Filtering/FilterDrawer.tsx
  src/services/ui/src/components/Opensearch/Filtering/index.tsx
  src/services/ui/src/components/Opensearch/Filtering/useFilterDrawer.ts
  src/services/ui/src/components/Opensearch/Table/index.tsx
  src/services/ui/src/components/Opensearch/useOpensearch.ts
  src/services/ui/src/components/Opensearch/utils.ts
  src/services/ui/src/components/Routing/Link.tsx
  src/services/ui/src/components/Routing/hooks.ts
  src/services/ui/src/components/Routing/index.ts
  src/services/ui/src/components/Routing/routes.ts
  src/services/ui/src/components/Routing/types.ts
  src/services/ui/src/components/Routing/utils.ts
  src/services/ui/src/components/Webform/index.tsx
  src/services/ui/src/hooks/useParams.ts
  src/services/ui/src/pages/actions/IssueRai.tsx
  src/services/ui/src/pages/actions/PackageActionForm.tsx
  src/services/ui/src/pages/actions/RespondToRai.tsx
  src/services/ui/src/pages/actions/ToggleRaiResponseWithdraw.tsx
  src/services/ui/src/pages/actions/WithdrawPackage.tsx
  src/services/ui/src/pages/actions/WithdrawRai.tsx
  src/services/ui/src/pages/actions/index.tsx
  src/services/ui/src/pages/create/create-breadcrumbs.ts
  src/services/ui/src/pages/create/external-landing/ExternalAppLandingPage.tsx
  src/services/ui/src/pages/create/options.tsx
  src/services/ui/src/pages/dashboard/Lists/spas/index.tsx
  src/services/ui/src/pages/dashboard/Lists/waivers/index.tsx
  src/services/ui/src/pages/dashboard/index.tsx
  src/services/ui/src/pages/detail/index.tsx
  src/services/ui/src/pages/form/modals.tsx
  src/services/ui/src/pages/welcome/index.tsx
  src/services/ui/src/utils/labelMappers.ts
Labels: refactor
