Repository Enterprise-CMCS/macpro-mako, pull requests merged in 2024-04, with the labels that each got.

#464 feat(OY2-27248): Submission FAQ Link
  src/services/ui/src/components/Footer/FAQFooter.tsx
  src/services/ui/src/components/Footer/index.tsx
  src/services/ui/src/features/actions/index.tsx
  src/services/ui/src/features/package-actions/ActionWrapper.tsx
  src/services/ui/src/features/submission/app-k/index.tsx
  src/services/ui/src/features/submission/spa/chip-intitial.tsx
  src/services/ui/src/features/submission/spa/medicaid-initial.tsx
  src/services/ui/src/features/submission/waiver/capitated/capitated-1915-b-waiver-amendment.tsx
  src/services/ui/src/features/submission/waiver/capitated/capitated-1915-b-waiver-initial.tsx
  src/services/ui/src/features/submission/waiver/capitated/capitated-1915-b-waiver-renewal.tsx
  src/services/ui/src/features/submission/waiver/contracting/contracting-1915-b-waiver-amendment.tsx
  src/services/ui/src/features/submission/waiver/contracting/contracting-1915-b-waiver-initial.tsx
  src/services/ui/src/features/submission/waiver/contracting/contracting-1915-b-waiver-renewal.tsx
  src/services/ui/src/features/welcome/index.tsx
Labels: type: FEAT, status: READY

#474 feat(errors): show error messaging as banner on failed submissions
  src/services/ui/src/components/Alert/index.tsx
  src/services/ui/src/components/Context/alertContext.tsx
  src/services/ui/src/features/actions/IssueRai.tsx
  src/services/ui/src/features/actions/RespondToRai.tsx
  src/services/ui/src/features/actions/ToggleRaiResponseWithdraw.tsx
  src/services/ui/src/features/actions/WithdrawPackage.tsx
  src/services/ui/src/features/actions/WithdrawRai.tsx
  src/services/ui/src/features/package-actions/IssueRai.tsx
  src/services/ui/src/features/package-actions/RespondToRai.tsx
  src/services/ui/src/features/package-actions/TemporaryExtension.tsx
  src/services/ui/src/features/package-actions/ToggleRaiResponseWithdraw.tsx
  src/services/ui/src/features/package-actions/WithdrawPackage.tsx
  src/services/ui/src/features/package-actions/WithdrawRai.tsx
  src/services/ui/src/features/package-actions/shared-components.tsx
  src/services/ui/src/features/submission/spa/chip-intitial.tsx
  src/services/ui/src/features/submission/spa/medicaid-initial.tsx
  src/services/ui/src/features/submission/waiver/capitated/capitated-1915-b-waiver-amendment.tsx
  src/services/ui/src/features/submission/waiver/capitated/capitated-1915-b-waiver-initial.tsx
  src/services/ui/src/features/submission/waiver/capitated/capitated-1915-b-waiver-renewal.tsx
  src/services/ui/src/features/submission/waiver/contracting/contracting-1915-b-waiver-amendment.tsx
  src/services/ui/src/features/submission/waiver/contracting/contracting-1915-b-waiver-initial.tsx
  src/services/ui/src/features/submission/waiver/contracting/contracting-1915-b-waiver-renewal.tsx
Labels: type: FEAT, status: TESTING

#416 feat(abp2a): add webform ABP 2a
  src/packages/shared-types/forms.ts
  src/services/api/handlers/getForm.ts
  src/services/api/webforms/ABP2A/index.ts
  src/services/api/webforms/ABP2A/v202401.ts
  src/services/api/webforms/index.ts
  src/services/ui/e2e/tests/a11y/index.spec.ts
  src/services/ui/src/components/Inputs/checkbox.tsx
  src/services/ui/src/features/webforms/WebformsList.tsx
Labels: In Testing, type: FEAT, status: TESTING

#465 fix(filters): Offset date range filter to UTC
  src/services/ui/src/components/Opensearch/main/Filtering/Chipbar/index.tsx
  src/services/ui/src/components/Opensearch/main/Filtering/Drawer/Filterable/DateRange.tsx
Labels: type: FIX, status: TESTING

#475 feat(abp2b): add abp2b to webforms list
  src/services/api/webforms/ABP2B/index.ts
  src/services/api/webforms/ABP2B/v202401.ts
  src/services/api/webforms/index.ts
  src/services/ui/e2e/tests/a11y/index.spec.ts
  src/services/ui/src/components/Inputs/checkbox.tsx
  src/services/ui/src/components/Inputs/form.tsx
  src/services/ui/src/components/RHF/utils/validator.ts
Labels: type: FEAT, status: READY

#488 feat(forms): Additional Info dynamic and 502-ready character counter
  src/services/ui/src/features/actions/IssueRai.tsx
  src/services/ui/src/features/actions/RespondToRai.tsx
  src/services/ui/src/features/actions/WithdrawPackage.tsx
  src/services/ui/src/features/actions/WithdrawRai.tsx
  src/services/ui/src/features/actions/renderSlots.test.tsx
  src/services/ui/src/features/actions/renderSlots.tsx
  src/services/ui/src/features/package-actions/IssueRai.tsx
  src/services/ui/src/features/package-actions/RespondToRai.tsx
  src/services/ui/src/features/package-actions/TemporaryExtension.tsx
  src/services/ui/src/features/package-actions/UpdateId.tsx
  src/services/ui/src/features/package-actions/WithdrawPackage.tsx
  src/services/ui/src/features/package-actions/WithdrawRai.tsx
  src/services/ui/src/features/package-actions/shared-components.tsx
  src/services/ui/src/features/submission/app-k/index.tsx
  src/services/ui/src/features/submission/shared-components/AdditionalInfoInput.tsx
  src/services/ui/src/features/submission/shared-components/index.ts
  src/services/ui/src/features/submission/spa/chip-intitial.tsx
  src/services/ui/src/features/submission/spa/medicaid-initial.tsx
  src/services/ui/src/features/submission/waiver/capitated/capitated-1915-b-waiver-amendment.tsx
  src/services/ui/src/features/submission/waiver/capitated/capitated-1915-b-waiver-initial.tsx
  src/services/ui/src/features/submission/waiver/capitated/capitated-1915-b-waiver-renewal.tsx
  src/services/ui/src/features/submission/waiver/contracting/contracting-1915-b-waiver-amendment.tsx
  src/services/ui/src/features/submission/waiver/contracting/contracting-1915-b-waiver-initial.tsx
  src/services/ui/src/features/submission/waiver/contracting/contracting-1915-b-waiver-renewal.tsx
Labels: type: FEAT, status: TESTING

#492 feat(ABP 2c): Add the ABP 2c web form
  src/services/api/webforms/ABP2C/index.ts
  src/services/api/webforms/ABP2C/v202401.ts
  src/services/api/webforms/index.ts
  src/services/ui/src/components/RHF/RHFTextDisplay.tsx
  src/services/ui/src/components/RHF/utils/initializer.ts
Labels: type: FEAT, status: TESTING

#373 feat(ABP 5) Add the ABP 5 web form
  src/packages/shared-types/forms.ts
  src/packages/shared-types/inputs.ts
  src/services/api/webforms/ABP1/v202401.ts
  src/services/api/webforms/ABP1/v202402.ts
  src/services/api/webforms/ABP10/v202401.ts
  src/services/api/webforms/ABP11/v202401.ts
  src/services/api/webforms/ABP2A/v202401.ts
  src/services/api/webforms/ABP2B/v202401.ts
  src/services/api/webforms/ABP2C/v202401.ts
  src/services/api/webforms/ABP3/v202401.ts
  src/services/api/webforms/ABP3_1/v202401.ts
  src/services/api/webforms/ABP5/index.ts
  src/services/api/webforms/ABP5/v202401.ts
  src/services/api/webforms/index.ts
  src/services/ui/e2e/tests/a11y/index.spec.ts
  src/services/ui/src/components/Inputs/button.tsx
  src/services/ui/src/components/Inputs/checkbox.tsx
  src/services/ui/src/components/Inputs/textarea.tsx
  src/services/ui/src/components/RHF/FieldGroup.tsx
  src/services/ui/src/components/RHF/FormGroup.tsx
  src/services/ui/src/components/RHF/Section.tsx
  src/services/ui/src/components/RHF/Slot.tsx
  src/services/ui/src/features/webforms/WebFormBody.tsx
  src/services/ui/src/index.css
  src/services/ui/tailwind.config.js
Labels: type: FEAT, status: READY

#522 fix(ui): Minor fixes to FAQ links and detail fields
  src/services/ui/src/features/dashboard/Lists/spas/consts.tsx
  src/services/ui/src/features/dashboard/Lists/waivers/consts.tsx
  src/services/ui/src/features/package/package-details/hooks.tsx
  src/services/ui/src/features/selection-flow/external-landing/ExternalAppLandingPage.tsx
Labels: type: FIX, status: TESTING

#530 fix(actions): Update confirmation banner for TE submission
  src/services/ui/src/features/package-actions/lib/modules/temporary-extension/index.tsx
Labels: priority: LOW, type: FIX, status: READY

#516 fix(package actions): Incorrect display of document types for CHIP SPA for RAI Response
  src/packages/shared-types/attachments.ts
Labels: priority: LOW, type: FIX, status: TESTING

#523 refactor(attachments): Consolidate Attachment key/label Mapping
  src/packages/shared-types/attachments.ts
  src/services/ui/src/api/submissionService.test.ts
  src/services/ui/src/api/submissionService.ts
  src/services/ui/src/components/Form/fields/AttachmentsSection.tsx
  src/services/ui/src/features/package-actions/lib/modules/issue-rai/index.tsx
  src/services/ui/src/features/package-actions/lib/modules/respond-to-rai/spa/chip-rai.tsx
  src/services/ui/src/features/package-actions/lib/modules/respond-to-rai/spa/med-rai.tsx
  src/services/ui/src/features/package-actions/lib/modules/respond-to-rai/waiver/b-waiver-rai.tsx
  src/services/ui/src/features/package-actions/lib/modules/temporary-extension/index.tsx
  src/services/ui/src/features/package-actions/lib/modules/temporary-extension/legacy-page.tsx
  src/services/ui/src/features/package-actions/lib/modules/withdraw-package/index.tsx
  src/services/ui/src/features/package-actions/lib/modules/withdraw-package/spa/withdraw-chip-rai.tsx
  src/services/ui/src/features/package-actions/lib/modules/withdraw-rai/index.tsx
  src/services/ui/src/features/package/package-activity/index.tsx
  src/services/ui/src/utils/common-types.ts
Labels: priority: LOW, type: FIX, status: TESTING
