Repository Enterprise-CMCS/macpro-mako, pull requests merged in 2024-11, with the labels that each got.

#832 feat(unit-tests): add component unit tests
  react-app/src/components/DetailsSection/DetailsSection.test.tsx
  react-app/src/components/ErrorAlert/ErrorAlert.test.tsx
  react-app/src/components/Footer/FAQFooter.tsx
  react-app/src/components/Footer/Footer.test.tsx
  react-app/src/components/HowItWorks/HowItWorks.test.tsx
  react-app/src/components/LoadingSpinner/LoadingSpinner.test.tsx
  react-app/src/components/UsaBanner/UsaBanner.test.tsx
  react-app/src/components/UsaBanner/index.tsx
Labels: type: FEAT, status: READY

#822 fix(scroll-top): add logic to scroll up on page change
  react-app/src/components/DetailsSection/index.tsx
  react-app/src/components/Layout/index.tsx
  react-app/src/components/ScrollToTop/index.ts
  react-app/src/components/index.tsx
  react-app/src/features/dashboard/index.tsx
  react-app/src/hooks/index.ts
  react-app/src/hooks/useScrollToTop.ts
Labels: type: FIX, status: READY

#827 fix(time-discrepancy): Fixed status updates to match timestamps with activity
  react-app/src/features/package/package-details/hooks.tsx
Labels: type: FIX, status: READY

#844 feat(unit-testing): Tests for SearchForm & Breadcrumbs
  react-app/src/components/BreadCrumb/BreadCrumb.test.tsx
  react-app/src/components/SearchForm/SearchForm.test.tsx
  react-app/src/components/SearchForm/index.tsx
Labels: status: READY
