Repository Enterprise-CMCS/macpro-mako, pull requests merged in 2024-05, with the labels that each got.

#529 fix(actions): small fixes related to actions routing consolidation
  src/services/ui/src/components/Form/fields/DescriptionInput.tsx
  src/services/ui/src/components/Form/fields/SubjectInput.tsx
  src/services/ui/src/features/dashboard/Lists/renderCells/index.tsx
  src/services/ui/src/features/package-actions/lib/fieldsSwitch.ts
  src/services/ui/src/features/package-actions/lib/modules/respond-to-rai/waiver/b-waiver-rai.tsx
  src/services/ui/src/features/package-actions/lib/modules/withdraw-package/index.tsx
  src/services/ui/src/features/package-actions/lib/modules/withdraw-package/spa/withdraw-chip-rai.tsx
  src/services/ui/src/features/package-actions/lib/modules/withdraw-rai/index.tsx
  src/services/ui/src/features/package/package-actions/index.tsx
Labels: type: FIX, status: TESTING

#526 fix(actions): Update verbiage for various action modal/alerts
  src/services/ui/src/features/package-actions/lib/contentSwitch.ts
  src/services/ui/src/features/package-actions/lib/modules/temporary-extension/legacy-page.tsx
  src/services/ui/src/features/package-actions/lib/modules/withdraw-package/index.tsx
  src/services/ui/src/features/package-actions/lib/modules/withdraw-package/spa/withdraw-chip-rai.tsx
  src/services/ui/src/features/package-actions/lib/modules/withdraw-package/waiver/withdraw-waiver.tsx
  src/services/ui/src/features/submission/app-k/index.tsx
Labels: type: FIX, status: TESTING

#517 feat(Abp7): add abp7 to our webforms list
  src/services/api/webforms/ABP4/v202401.ts
  src/services/api/webforms/ABP7/index.ts
  src/services/api/webforms/ABP7/v202401.ts
  src/services/api/webforms/ABP9/v202401.ts
  src/services/api/webforms/index.ts
  src/services/ui/e2e/tests/a11y/index.spec.ts
Labels: In Testing, type: FEAT

#533 fix(webform styles): add HCD feedback to webform inputs and padding
  src/services/api/webforms/ABP1/v202402.ts
  src/services/api/webforms/ABP2A/v202401.ts
  src/services/api/webforms/ABP2B/v202401.ts
  src/services/api/webforms/ABP2C/v202401.ts
  src/services/ui/src/components/Inputs/checkbox.tsx
  src/services/ui/src/components/Inputs/radio-group.tsx
  src/services/ui/src/components/Inputs/select.tsx
  src/services/ui/src/components/RHF/Slot.tsx
  src/services/ui/src/features/webforms/WebFormBody.tsx
Labels: In Testing, type: FIX

#540 feat(rhf tests and refactor): rhf slot tests and refactor
  src/services/ui/src/components/Inputs/checkbox.tsx
  src/services/ui/src/components/Inputs/form.tsx
  src/services/ui/src/components/RHF/Slot.tsx
  src/services/ui/src/components/RHF/SlotField.tsx
  src/services/ui/src/components/RHF/tests/Slot.test.tsx
  src/services/ui/src/components/RHF/tests/SlotField.test.tsx
  src/services/ui/testing/setup.ts
Labels: type: FEAT, type: REFACTOR, status: READY

#543 fix(checkbox styled label): add logic to add styled label to select which fixes required validation on abp2a & abp2b
  src/packages/shared-types/forms.ts
  src/services/api/webforms/ABP2A/v202401.ts
  src/services/api/webforms/ABP2B/v202401.ts
  src/services/ui/src/components/RHF/Slot.tsx
Labels: In Testing, type: FIX, status: READY

#532 feat(sync-with-external-systems): Synchronize the react code with external data systems
  src/packages/shared-types/action-type.ts
  src/packages/shared-types/index.ts
  src/packages/shared-utils/package-check.ts
  src/packages/shared-utils/tests/package-check.test.ts
  src/services/ui/src/components/BreadCrumb/create-breadcrumbs.ts
  src/services/ui/src/components/Form/fields/FormButtons.tsx
  src/services/ui/src/components/Opensearch/main/useOpensearch.ts
  src/services/ui/src/consts/index.ts
  src/services/ui/src/consts/spa-id-regex.ts
  src/services/ui/src/features/dashboard/Lists/renderCells/index.tsx
  src/services/ui/src/features/package-actions/ActionForm.tsx
  src/services/ui/src/features/package-actions/ActionPage.tsx
  src/services/ui/src/features/package-actions/actions-breadcrumbs.ts
  src/services/ui/src/features/package-actions/legacy-shared-components.tsx
  src/services/ui/src/features/package-actions/lib/index.ts
  src/services/ui/src/features/package-actions/lib/modules/complete-intake/index.tsx
  src/services/ui/src/features/package-actions/lib/modules/issue-rai/index.tsx
  src/services/ui/src/features/package-actions/lib/modules/respond-to-rai/index.tsx
  src/services/ui/src/features/package-actions/lib/modules/temporary-extension/index.tsx
  src/services/ui/src/features/package-actions/lib/modules/temporary-extension/legacy-page.tsx
  src/services/ui/src/features/package-actions/lib/modules/toggle-rai-withdraw/index.tsx
  src/services/ui/src/features/package-actions/lib/modules/update-id/index.tsx
  src/services/ui/src/features/package-actions/lib/modules/withdraw-package/index.tsx
  src/services/ui/src/features/package-actions/lib/modules/withdraw-rai/index.tsx
  src/services/ui/src/features/package-actions/lib/successCheckSwitch.ts
  src/services/ui/src/features/package/admin-changes/index.tsx
  src/services/ui/src/features/package/package-activity/index.tsx
  src/services/ui/src/features/submission/app-k/index.tsx
  src/services/ui/src/features/submission/spa/chip-intitial.tsx
  src/services/ui/src/features/submission/spa/medicaid-initial.tsx
  src/services/ui/src/features/submission/waiver/capitated/capitated-1915-b-waiver-amendment.tsx
  src/services/ui/src/features/submission/waiver/capitated/capitated-1915-b-waiver-initial.tsx
  src/services/ui/src/features/submission/waiver/capitated/capitated-1915-b-waiver-renewal.tsx
  src/services/ui/src/features/submission/waiver/contracting/contracting-1915-b-waiver-amendment.tsx
  src/services/ui/src/features/submission/waiver/contracting/contracting-1915-b-waiver-initial.tsx
  src/services/ui/src/features/submission/waiver/contracting/contracting-1915-b-waiver-renewal.tsx
  src/services/ui/src/utils/Poller/DataPoller.ts
  src/services/ui/src/utils/Poller/documentPoller.ts
  src/services/ui/src/utils/crumbs.ts
  src/services/ui/src/utils/location.ts
  src/services/ui/src/utils/stripQueryString.ts
  src/services/ui/src/utils/user.ts
Labels: type: FEAT, status: READY, status: TESTING

#550 fix(508 details): add missing spec files to a11y testing and run 508 test on pages
  src/services/ui/e2e/tests/a11y/index.spec.ts
  src/services/ui/src/components/Inputs/checkbox.tsx
  src/services/ui/src/components/MaintenanceBanner/index.tsx
  src/services/ui/src/index.css
Labels: type: FIX, status: READY

#511 fix(appk): figma updates, changelog, withdraw labels
  src/packages/shared-types/opensearch/changelog/index.ts
  src/packages/shared-types/opensearch/main/transforms/remove-appk-child.ts
  src/services/api/handlers/appkNewSubmission.ts
  src/services/data/handlers/sinkChangelog.ts
  src/services/data/handlers/sinkMain.ts
  src/services/ui/src/features/package/package-activity/index.tsx
  src/services/ui/src/features/package/package-details/appk.tsx
  src/services/ui/src/features/submission/app-k/consts.ts
  src/services/ui/src/features/submission/app-k/index.tsx
  src/services/ui/src/features/submission/app-k/slots.tsx
Labels: priority: HIGH, type: FIX, status: READY

#553 fix(OY2-27896): temporary extension faq footer
  src/services/ui/src/features/package-actions/lib/modules/temporary-extension/legacy-page.tsx
Labels: priority: LOW, type: FIX, status: READY

#515 feat(validate-on-change): Change Validation Mode of React Hook Form to "onChange"
  src/services/api/handlers/itemExists.ts
  src/services/ui/src/api/itemExists.ts
  src/services/ui/src/components/Form/content/ContentWrappers.tsx
  src/services/ui/src/features/package-actions/lib/modules/temporary-extension/index.tsx
  src/services/ui/src/features/package-actions/lib/modules/temporary-extension/legacy-components.tsx
  src/services/ui/src/features/package-actions/lib/modules/temporary-extension/legacy-page.tsx
  src/services/ui/src/features/submission/spa/chip-intitial.tsx
  src/services/ui/src/features/submission/spa/medicaid-initial.tsx
  src/services/ui/src/features/submission/waiver/capitated/capitated-1915-b-waiver-amendment.tsx
  src/services/ui/src/features/submission/waiver/capitated/capitated-1915-b-waiver-initial.tsx
  src/services/ui/src/features/submission/waiver/capitated/capitated-1915-b-waiver-renewal.tsx
  src/services/ui/src/features/submission/waiver/contracting/contracting-1915-b-waiver-amendment.tsx
  src/services/ui/src/features/submission/waiver/contracting/contracting-1915-b-waiver-initial.tsx
  src/services/ui/src/features/submission/waiver/contracting/contracting-1915-b-waiver-renewal.tsx
  src/services/ui/src/utils/zod.ts
  src/services/ui/src/zodIdValidator.ts
Labels: type: FEAT, status: READY

#557 fix(OY2-27839): CSV export search filter
  src/services/ui/src/components/Opensearch/main/Filtering/Export/index.tsx
Labels: priority: LOW, type: FIX, status: READY

#542 restyle(dash): Make Table Responsive
  src/services/ui/src/components/Dialog/index.tsx
  src/services/ui/src/components/Inputs/calendar.tsx
  src/services/ui/src/components/Inputs/date-picker.tsx
  src/services/ui/src/components/Layout/index.tsx
  src/services/ui/src/components/Opensearch/main/Filtering/Drawer/Filterable/DateRange.tsx
  src/services/ui/src/components/Opensearch/main/Filtering/Drawer/index.tsx
  src/services/ui/src/components/Opensearch/main/Filtering/Export/index.tsx
  src/services/ui/src/components/Opensearch/main/Filtering/index.tsx
  src/services/ui/src/components/Opensearch/main/Table/index.tsx
  src/services/ui/src/components/Opensearch/main/index.tsx
  src/services/ui/src/components/Pagination/index.tsx
  src/services/ui/src/components/SearchForm/index.tsx
  src/services/ui/src/components/Tabs/index.tsx
  src/services/ui/src/features/dashboard/Lists/waivers/consts.tsx
  src/services/ui/src/features/dashboard/index.tsx
  src/services/ui/tailwind.config.js
Labels: priority: MED, type: FIX, status: TESTING
