Repository Enterprise-CMCS/macpro-mako, pull requests merged in 2024-10, with the labels that each got.

#793 feat: add er spa
  lib/libs/webforms/ER/index.ts
  lib/libs/webforms/ER/v202401.ts
  lib/libs/webforms/index.ts
  lib/packages/shared-types/forms.ts
  react-app/src/components/RHF/Section.tsx
  react-app/src/components/RHF/dependencyWrapper.tsx
Labels: type: FEAT, status: READY, status: TESTING

#789 fix(cs8): add feedback from QA
  lib/libs/webforms/CS8/v202401.ts
Labels: status: READY

#799 fix(cs3-message-overlap): add changes ben suggested
  lib/libs/webforms/CS3/v202401.ts
  lib/libs/webforms/CS7/v202401.ts
Labels: status: READY, status: TESTING

#806 fix: abp2c spacing and hcd changes
  lib/libs/webforms/ABP2C/v202401.ts
  react-app/src/components/RHF/FormGroup.tsx
  react-app/src/components/RHF/Slot.tsx
  react-app/src/components/RHF/tests/Slot.test.tsx
Labels: status: READY, status: TESTING

#823 feat(test): Tests for Pagination
  react-app/src/components/Pagination/Pagination.test.tsx
  react-app/src/components/Pagination/index.tsx
Labels: type: FEAT, status: READY
