Repository Enterprise-CMCS/macpro-mako, pull requests merged in 2024-03, with the labels that each got.

#419 test(ui): Improve unit test coverage for `services/ui`
  package.json
  src/services/ui/src/api/mocks/index.ts
  src/services/ui/src/api/mocks/item.ts
  src/services/ui/src/api/mocks/submit.ts
  src/services/ui/src/api/submissionService.test.ts
  src/services/ui/src/api/submissionService.ts
  src/services/ui/src/api/useGetItem.test.ts
  src/services/ui/src/api/useGetItem.ts
  src/services/ui/src/api/useGetUser.test.ts
  src/services/ui/src/api/useGetUser.ts
  yarn.lock
Labels: type: CHORE, status: READY

#423 test(shared-utils): Improve test coverage for `packages/shared-utils`
  src/packages/shared-utils/index.ts
  src/packages/shared-utils/package-actions/getAvailableActions.ts
  src/packages/shared-utils/package-actions/rules.ts
  src/packages/shared-utils/package-check.ts
  src/packages/shared-utils/tests/package-check.test.ts
  src/packages/shared-utils/tests/rules.test.ts
  src/packages/shared-utils/tests/seatool-date-helper.test.ts
  src/packages/shared-utils/tests/testData.ts
  src/packages/shared-utils/tests/user-helper.test.ts
  src/packages/shared-utils/user-helper.ts
  src/services/ui/src/api/useGetUser.test.ts
  src/services/ui/src/api/useGetUser.ts
  src/services/ui/vite.config.ts
Labels: type: CHORE, status: READY

#418 fix(APPK): bugs · refactor · cleanup
  src/packages/shared-types/opensearch/main/index.ts
  src/packages/shared-utils/package-check.ts
  src/services/api/handlers/appkNewSubmission.ts
  src/services/api/handlers/item.ts
  src/services/api/handlers/packageActions.ts
  src/services/api/libs/package/appk.ts
  src/services/api/libs/package/index.ts
  src/services/api/serverless.yml
  src/services/ui/src/api/useGetItem.ts
  src/services/ui/src/components/BreadCrumb/create-breadcrumbs.ts
  src/services/ui/src/components/Opensearch/utils.ts
  src/services/ui/src/components/Routing/routes.ts
  src/services/ui/src/features/package/admin-changes/index.tsx
  src/services/ui/src/features/package/index.tsx
  src/services/ui/src/features/package/package-activity/hook.ts
  src/services/ui/src/features/package/package-activity/index.tsx
  src/services/ui/src/features/package/package-details/appk.tsx
  src/services/ui/src/features/package/package-details/index.tsx
  src/services/ui/src/features/selection-flow/options.tsx
  src/services/ui/src/features/submission/app-k/DragNDrop.tsx
  src/services/ui/src/features/submission/app-k/consts.ts
  src/services/ui/src/features/submission/app-k/index.tsx
  src/services/ui/src/features/submission/app-k/slots.tsx
  src/services/ui/src/features/submission/spa/chip-intitial.tsx
  src/services/ui/src/router.tsx
  src/services/ui/src/utils/labelMappers.ts
  src/services/ui/src/utils/zod.ts
Labels: type: FIX, status: READY

#417 fix(content-revisions): Content revisions for ABP 1, 3, & 3.1
  src/services/api/webforms/ABP1/v202402.ts
  src/services/api/webforms/ABP3/v202401.ts
  src/services/api/webforms/ABP3_1/v202401.ts
Labels: In Testing, type: FIX, status: READY

#448 feat: text slot and desc changes
  src/packages/shared-types/forms.ts
  src/services/ui/src/components/Inputs/checkbox.tsx
  src/services/ui/src/components/RHF/RHFTextDisplay.tsx
  src/services/ui/src/components/RHF/Slot.tsx
  src/services/ui/src/components/RHF/index.ts
Labels: type: FEAT, status: READY

#443 fix(OY2-25752): os export hide columns
  src/packages/shared-types/attachments.ts
  src/packages/shared-types/opensearch/_.ts
  src/packages/shared-types/opensearch/changelog/index.ts
  src/packages/shared-types/opensearch/main/index.ts
  src/packages/shared-types/opensearch/subtypes/index.ts
  src/packages/shared-types/opensearch/types/index.ts
  src/services/api/handlers/appkNewSubmission.ts
  src/services/ui/src/components/ExportButton/index.tsx
  src/services/ui/src/components/Form/content.tsx
  src/services/ui/src/components/Opensearch/main/Filtering/Drawer/consts.ts
  src/services/ui/src/components/Opensearch/main/Filtering/Drawer/hooks.ts
  src/services/ui/src/components/Opensearch/main/Filtering/Export/hooks.ts
  src/services/ui/src/components/Opensearch/main/Filtering/Export/index.tsx
  src/services/ui/src/components/Opensearch/main/Filtering/index.tsx
  src/services/ui/src/components/Opensearch/main/Settings/Visibility.tsx
  src/services/ui/src/components/Opensearch/main/Table/index.tsx
  src/services/ui/src/components/Opensearch/main/Table/types.ts
  src/services/ui/src/components/Opensearch/main/index.ts
  src/services/ui/src/components/Opensearch/main/index.tsx
  src/services/ui/src/components/index.tsx
  src/services/ui/src/features/dashboard/Lists/spas/consts.tsx
  src/services/ui/src/features/dashboard/Lists/spas/index.tsx
  src/services/ui/src/features/dashboard/Lists/waivers/consts.tsx
  src/services/ui/src/features/dashboard/Lists/waivers/index.tsx
  src/services/ui/src/features/submission/app-k/consts.ts
  src/services/ui/src/features/submission/app-k/index.tsx
Labels: type: FIX, status: READY

#447 bug(error-messages): Fix error messages for incorrect initial ID on waiver amendment and renewals
  src/services/ui/src/utils/zod.ts
Labels: type: FIX, status: TESTING

#453 feat(os): add final disposition date + csv transform headers
  src/packages/shared-types/statusHelper.ts
  src/services/ui/src/components/Opensearch/main/Filtering/Drawer/consts.ts
  src/services/ui/src/components/Opensearch/main/Filtering/Drawer/hooks.ts
  src/services/ui/src/components/Opensearch/main/Filtering/Export/index.tsx
  src/services/ui/src/components/Opensearch/main/useOpensearch.ts
  src/services/ui/src/features/dashboard/Lists/spas/consts.tsx
  src/services/ui/src/features/dashboard/Lists/waivers/consts.tsx
Labels: type: FEAT, status: READY

#455 fix(waivers): only allow Renewal and Initial waiver ids for Renew/Amend actions
  src/services/ui/src/api/mocks/item.ts
  src/services/ui/src/api/useGetItem.test.ts
  src/services/ui/src/api/useGetItem.ts
  src/services/ui/src/utils/zod.ts
Labels: type: FIX, status: READY

#468 feat(key-structure): add an agreed upon key structure for our forms
  docs/docs/webforms.md
  src/services/api/webforms/ABP1/v202402.ts
  src/services/api/webforms/ABP10/v202401.ts
  src/services/api/webforms/ABP11/v202401.ts
  src/services/api/webforms/ABP3/v202401.ts
  src/services/api/webforms/ABP3_1/v202401.ts
Labels: type: FEAT, status: READY
