Repository Enterprise-CMCS/macpro-mako, pull requests merged in 2024-01, with the labels that each got.

#299 feat(actions): Restructure ActionFormIndex and utilize ModalContext in forms
  src/services/ui/src/pages/actions/IssueRai.tsx
  src/services/ui/src/pages/actions/PackageActionForm.tsx
  src/services/ui/src/pages/actions/RespondToRai.tsx
  src/services/ui/src/pages/actions/ToggleRaiResponseWithdraw.tsx
  src/services/ui/src/pages/actions/WithdrawPackage.tsx
  src/services/ui/src/pages/actions/WithdrawRai.tsx
  src/services/ui/src/pages/actions/actions-breadcrumbs.ts
  src/services/ui/src/pages/actions/index.tsx
  src/services/ui/src/pages/detail/index.tsx
  src/services/ui/src/pages/form/modals.tsx
Labels: refactor

#315 feat(actions): Actions available for CHIP SPA
  src/packages/shared-utils/package-actions/getAvailableActions.ts
  src/services/ui/src/hooks/useActionFormController.ts
  src/services/ui/src/lib/common-types.ts
  src/services/ui/src/pages/actions/IssueRai.tsx
  src/services/ui/src/pages/actions/RespondToRai.tsx
  src/services/ui/src/pages/actions/WithdrawPackage.tsx
  src/services/ui/src/pages/actions/WithdrawRai.tsx
  src/services/ui/src/pages/actions/index.tsx
  src/services/ui/src/pages/actions/renderSlots.tsx
  src/services/ui/src/pages/actions/setups/_.ts
  src/services/ui/src/pages/actions/setups/index.ts
  src/services/ui/src/pages/actions/setups/setupIssueRai.ts
  src/services/ui/src/pages/actions/setups/setupRespondToRai.ts
  src/services/ui/src/pages/actions/setups/setupWithdrawPackage.ts
  src/services/ui/src/pages/actions/setups/setupWithdrawRai.ts
  src/services/ui/src/pages/actions/template.tsx
  src/services/ui/src/pages/form/zod.ts
Labels: In Testing, Ready

#317 feat(OY2-26082): Package actions FE
  src/services/api/handlers/getAttachmentUrl.ts
  src/services/api/libs/auth/user.ts
  src/services/api/libs/package/changelog.ts
  src/services/ui/src/components/Inputs/button.tsx
  src/services/ui/src/pages/detail/admin-changes/AdminChanges.tsx
  src/services/ui/src/pages/detail/admin-changes/index.tsx
  src/services/ui/src/pages/detail/index.tsx
  src/services/ui/src/pages/detail/package-activity/PackageActivity.tsx
  src/services/ui/src/pages/detail/package-activity/hook.ts
  src/services/ui/src/pages/detail/package-activity/index.tsx
Labels: enhancement, Ready

#322 fix(actions): Updating action template and forms content
  src/packages/shared-utils/index.ts
  src/packages/shared-utils/is-state-user.ts
  src/packages/shared-utils/package-actions/rules.ts
  src/packages/shared-utils/user-helper.ts
  src/services/ui/src/hooks/useActionFormController.ts
  src/services/ui/src/pages/actions/IssueRai.tsx
  src/services/ui/src/pages/actions/RespondToRai.tsx
  src/services/ui/src/pages/actions/WithdrawPackage.tsx
  src/services/ui/src/pages/actions/WithdrawRai.tsx
  src/services/ui/src/pages/actions/index.tsx
  src/services/ui/src/pages/actions/setups/_.ts
  src/services/ui/src/pages/actions/setups/setupIssueRai.ts
  src/services/ui/src/pages/actions/setups/setupRespondToRai.ts
  src/services/ui/src/pages/actions/setups/setupWithdrawPackage.ts
  src/services/ui/src/pages/actions/setups/setupWithdrawRai.ts
  src/services/ui/src/pages/actions/template.tsx
  src/services/ui/src/pages/detail/index.tsx
  src/services/ui/src/pages/form/zod.ts
Labels: In Testing

#334 refactor(app-router): finish overhaul of routing
  src/services/ui/src/components/Layout/index.tsx
  src/services/ui/src/components/Routing/consts.ts
  src/services/ui/src/pages/create/external-landing/ExternalAppLandingPage.tsx
  src/services/ui/src/pages/faq/content/oneMACFAQContent.tsx
  src/services/ui/src/pages/form/chip-form.tsx
  src/services/ui/src/pages/form/content.tsx
  src/services/ui/src/pages/form/form-breadcrumbs.ts
  src/services/ui/src/pages/form/medicaid-form.tsx
  src/services/ui/src/pages/welcome/index.tsx
  src/services/ui/src/router.tsx
  src/services/ui/src/routes.ts
  src/services/ui/src/utils/crumbs.ts
Labels: refactor

#333 feat(abp 10): create abp 10 General assurances webform
  src/services/api/layers/ABP10/v1.ts
  src/services/ui/src/components/Webform/index.tsx
Labels: enhancement

#338 fix(actions): Title update for RAI Response action
  src/services/ui/src/pages/actions/RespondToRai.tsx
  src/services/ui/src/pages/actions/WithdrawPackage.tsx
Labels: bug, Ready

#340 fix(checkbox): using formContext hook outside of forms
  src/services/ui/src/components/RHF/dependencyWrapper.tsx
Labels: bug, Ready

#339 feat(abp1 v2): create second version of abp 1 with adjustements from hcd
  src/services/api/layers/ABP1/v2.ts
  src/services/ui/src/components/Webform/index.tsx
Labels: enhancement, Ready

#329 feat(read-only): add read only mode to webforms
  src/services/ui/src/components/Webform/footer.tsx
  src/services/ui/src/components/Webform/index.tsx
  src/services/ui/src/components/Webform/useReadOnlyUser.tsx
Labels: type: FEAT

#347 feat(OY2-27179): 'Initial Intake Needed' sub status
  src/packages/shared-types/opensearch/_.ts
  src/packages/shared-types/opensearch/changelog/index.ts
  src/packages/shared-types/opensearch/main/index.ts
  src/packages/shared-types/opensearch/main/transforms/seatool.ts
  src/services/ui/src/components/Opensearch/main/Filtering/Chipbar/index.tsx
  src/services/ui/src/components/Opensearch/main/Filtering/Drawer/Filterable/Boolean.tsx
  src/services/ui/src/components/Opensearch/main/Filtering/Drawer/Filterable/DateRange.tsx
  src/services/ui/src/components/Opensearch/main/Filtering/Drawer/Filterable/Multicheck.tsx
  src/services/ui/src/components/Opensearch/main/Filtering/Drawer/Filterable/Select.tsx
  src/services/ui/src/components/Opensearch/main/Filtering/Drawer/Filterable/index.ts
  src/services/ui/src/components/Opensearch/main/Filtering/Drawer/consts.ts
  src/services/ui/src/components/Opensearch/main/Filtering/Drawer/hooks.ts
  src/services/ui/src/components/Opensearch/main/Filtering/Drawer/index.tsx
  src/services/ui/src/components/Opensearch/main/Filtering/Export/hooks.ts
  src/services/ui/src/components/Opensearch/main/Filtering/Export/index.tsx
  src/services/ui/src/components/Opensearch/main/Filtering/consts.ts
  src/services/ui/src/components/Opensearch/main/Filtering/index.tsx
  src/services/ui/src/components/Opensearch/main/Filtering/useFilterDrawer.ts
  src/services/ui/src/components/Opensearch/main/Table/index.tsx
  src/services/ui/src/components/Opensearch/main/types.ts
  src/services/ui/src/components/Opensearch/utils.ts
  src/services/ui/src/pages/dashboard/Lists/spas/consts.tsx
  src/services/ui/src/pages/dashboard/Lists/spas/index.tsx
  src/services/ui/src/pages/dashboard/Lists/waivers/index.tsx
  src/services/ui/src/pages/detail/index.tsx
Labels: priority: HIGH, type: FEAT, status: READY

#348 feat(OY2-27029 & OY2-27030): Implement Basic Email Sending Functionality & Implement Retry Mechanism for Failed Emails
  docs/assets/diagram.svg
  docs/docs/services/email.md
  serverless-compose.yml
  src/services/email/.eslintrc.js
  src/services/email/handlers/processEmailEvents.js
  src/services/email/handlers/processEmails.js
  src/services/email/package.json
  src/services/email/serverless.yml
  yarn.lock
Labels: priority: MED, type: FEAT, status: READY
