Repository Enterprise-CMCS/macpro-mako, pull requests merged in 2024-09, with the labels that each got.

#728 fix(g2 divider fix): fix divider issues on g2a and g2b
  lib/libs/webforms/G2A/v202401.ts
  lib/libs/webforms/G2B/v202401.ts
Labels: type: FIX, status: READY

#762 feat(user counties): Add get counties hook to pull user state counties
  lib/packages/shared-types/inputs.ts
  lib/packages/shared-types/states.ts
  react-app/src/api/index.ts
  react-app/src/api/useGetCounties.ts
  react-app/src/api/useGetUser.ts
  react-app/src/components/Context/userContext.tsx
  react-app/src/components/RHF/SlotField.tsx
Labels: type: FEAT, status: READY

#770 fix (g2c): qa changes to match figma
  lib/libs/webforms/G2C/v202401.ts
  lib/packages/shared-types/forms.ts
  react-app/src/components/RHF/FieldArray.tsx
  react-app/src/components/RHF/RHFTextDisplay.tsx
Labels: type: FIX, status: TESTING

#776 feat(Cs8): Add cs8 to our webforms list
  lib/libs/webforms/CS8/index.ts
  lib/libs/webforms/CS8/v202401.ts
  lib/libs/webforms/index.ts
  test/e2e/tests/a11y/index.spec.ts
Labels: type: FEAT, status: READY

#777 feat(webforms): Add CS 9 to webforms
  lib/libs/webforms/CS9/index.ts
  lib/libs/webforms/CS9/v202401.ts
  lib/libs/webforms/index.ts
Labels: type: FEAT, status: READY

#782 fix(fieldArray-focus): add logic to not auto focus when fieldarray is first added
  react-app/src/components/RHF/FieldArray.tsx
Labels: type: FIX, status: READY

#790 fix(cs7-updates): Cs7 updates
  lib/libs/webforms/CS3/v202401.ts
  lib/libs/webforms/CS7/v202401.ts
  lib/packages/shared-types/forms.ts
  react-app/src/components/RHF/utils/additionalRules.ts
  test/e2e/tests/a11y/index.spec.ts
Labels: status: READY
