Repository Enterprise-CMCS/macpro-mako, pull requests merged in 2024-07, with the labels that each got.

#599 feat(g1): add g1 form to our webforms list
  src/packages/shared-types/forms.ts
  src/services/api/webforms/G1/index.ts
  src/services/api/webforms/G1/v202401.ts
  src/services/api/webforms/index.ts
  src/services/ui/e2e/tests/a11y/index.spec.ts
  src/services/ui/src/components/RHF/Document.tsx
  src/services/ui/tailwind.config.js
Labels: type: FEAT, status: READY

#598 fix: (Abp2c fix): abpc2 requested changes from HCD
  src/services/api/webforms/ABP2C/v202401.ts
  src/services/ui/tailwind.config.js
Labels: type: FIX, status: READY

#591 fix(abp1-fixes): add hcd feedback to ABP1
  src/packages/shared-types/forms.ts
  src/packages/shared-types/inputs.ts
  src/services/api/webforms/ABP1/v202402.ts
  src/services/ui/src/components/Inputs/button.tsx
  src/services/ui/src/components/Inputs/input.tsx
  src/services/ui/src/components/RHF/Slot.tsx
  src/services/ui/src/components/RHF/SlotField.tsx
  src/services/ui/src/components/RHF/dependencyWrapper.tsx
  src/services/ui/src/features/webforms/WebFormBody.tsx
Labels: type: FIX, status: READY

#612 fix(ui): change `.opd` to `.xlsx`
  src/services/ui/src/components/Form/old-content.tsx
Labels: type: FIX, status: READY

#615 fix(ui): add "If you leave this page, you will lose your progress on this form" text
  src/services/ui/src/features/package-actions/lib/modules/withdraw-package/index.tsx
  src/services/ui/src/features/package-actions/lib/modules/withdraw-package/spa/withdraw-chip-rai.tsx
  src/services/ui/src/features/package-actions/lib/modules/withdraw-rai/index.tsx
Labels: type: FIX, status: READY

#610 feat(ui): Timeout Modal for User Inactivity
  src/services/ui/package.json
  src/services/ui/src/components/TimeoutModal/index.tsx
  src/services/ui/src/components/index.tsx
  src/services/ui/src/hooks/useCountdown.ts
  src/services/ui/src/hooks/useIdle.ts
  src/services/ui/src/main.tsx
  yarn.lock
Labels: type: FEAT, status: READY

#607 feat(G3 webform): add g3 to our webforms list
  src/services/api/webforms/G3/index.ts
  src/services/api/webforms/G3/v202401.ts
  src/services/api/webforms/index.ts
  src/services/ui/e2e/tests/a11y/index.spec.ts
  src/services/ui/src/components/RHF/Section.tsx
Labels: type: FEAT, status: READY

#627 chore(vitest): Updating to the latest version of vitest in all services
  src/libs/package.json
  src/packages/shared-types/package.json
  src/services/api/handlers/item.ts
  src/services/email/package.json
  src/services/ui/package.json
  yarn.lock
Labels: type: DEPS

#628 fix(fix appk button): fix appk button
  src/services/ui/src/features/submission/app-k/slots.tsx
Labels: type: FIX

#631 fix(ui): Display Full State Names
  src/services/ui/src/features/package/package-details/hooks.tsx
  src/services/ui/src/features/profile/index.tsx
  src/services/ui/src/utils/stateNames.ts
Labels: type: FIX, status: READY

#621 fix(ui): clicking on side links refreshed page and dismissed banner
  src/services/ui/src/features/package/admin-changes/index.tsx
  src/services/ui/src/features/package/hooks.tsx
  src/services/ui/src/features/package/package-details/index.tsx
Labels: type: FIX, status: READY

#640 fix(g3-fixes): G3 fixes found by padma in val
  src/services/api/webforms/G3/v202401.ts
Labels: type: FIX, status: READY

#638 fix(ui): update disable/enable banner wording
  src/services/ui/src/features/package-actions/lib/modules/toggle-rai-withdraw/index.tsx
Labels: type: FIX, status: READY

#646 feat: add g2a webform and additional testing
  src/packages/shared-types/forms.ts
  src/services/api/webforms/ABP1/v202401.ts
  src/services/api/webforms/ABP1/v202402.ts
  src/services/api/webforms/G2A/index.ts
  src/services/api/webforms/G2A/v202401.ts
  src/services/api/webforms/index.ts
  src/services/ui/src/components/RHF/Field.tsx
  src/services/ui/src/components/RHF/FieldArray.tsx
  src/services/ui/src/components/RHF/FieldGroup.tsx
  src/services/ui/src/components/RHF/SlotField.tsx
  src/services/ui/src/components/RHF/index.ts
  src/services/ui/src/components/RHF/tests/FieldArray.test.tsx
  src/services/ui/src/components/RHF/tests/RHFTextDisplay.test.tsx
  src/services/ui/src/components/RHF/tests/Section.test.tsx
  src/services/ui/src/components/RHF/tests/additionalRules.test.ts
  src/services/ui/src/components/RHF/tests/initializer.test.tsx
  src/services/ui/src/components/RHF/utils/additionalRules.ts
  src/services/ui/src/components/RHF/utils/index.ts
  src/services/ui/src/components/RHF/utils/initializer.ts
Labels: status: TESTING

#602 fix(email): wording fixes
  src/services/email/libs/bundle-lib.js
  src/services/email/libs/data-lib.js
  src/services/email/ses-email-templates/index.js
Labels: priority: MED, type: FIX, status: READY

#658 fix(abp9-10): fix HCD feedback items with abp9 & 10
  src/services/api/webforms/ABP9/v202401.ts
Labels: type: FIX, status: READY

#659 feat(unit-standards): add styling for unit standards
  src/services/ui/src/components/Inputs/input.tsx
Labels: type: FEAT, status: READY

#657 fix(hcd-abp6): fix issues from hcd feedback
  src/services/api/webforms/ABP6/v202401.ts
Labels: type: FIX, status: READY

#644 fix(ui): waivers tab fix
  src/packages/shared-types/authority.ts
  src/services/ui/e2e/tests/a11y/index.spec.ts
  src/services/ui/src/api/submissionService.test.ts
  src/services/ui/src/api/submissionService.ts
  src/services/ui/src/api/useGetItem.ts
  src/services/ui/src/consts/index.ts
  src/services/ui/src/consts/spa-id-regex.ts
  src/services/ui/src/features/dashboard/Lists/renderCells/index.tsx
  src/services/ui/src/features/dashboard/Lists/spas/consts.tsx
  src/services/ui/src/features/dashboard/Lists/waivers/consts.tsx
  src/services/ui/src/features/package-actions/ActionPage.tsx
  src/services/ui/src/features/package-actions/actions-breadcrumbs.ts
  src/services/ui/src/features/package-actions/lib/index.ts
  src/services/ui/src/features/package-actions/lib/modules/temporary-extension/legacy-page.tsx
  src/services/ui/src/features/package/index.tsx
  src/services/ui/src/features/package/package-details/appk.tsx
  src/services/ui/src/features/submission/spa/chip-intitial.tsx
  src/services/ui/src/features/submission/spa/medicaid-initial.tsx
  src/services/ui/src/router.tsx
  src/services/ui/src/utils/crumbs.ts
  src/services/ui/src/utils/formOrigin.ts
Labels: type: FIX, status: READY

#650 fix(ui): switch modal buttons
  src/services/ui/src/components/Context/modalContext.tsx
  src/services/ui/src/components/Dialog/index.tsx
  src/services/ui/src/components/Modal/ConfirmationModal.tsx
  src/services/ui/src/features/package-actions/lib/modules/withdraw-package/index.tsx
  src/services/ui/src/features/submission/waiver/shared-components/SubmitAndCancelBtnSection.tsx
  src/services/ui/src/utils/index.ts
Labels: type: FIX, status: READY

#682 chore(ui): update `vite`
  src/services/ui/package.json
  yarn.lock
Labels: type: FIX, status: READY

#663 fix(ui): enable super user ID editing
  src/packages/shared-utils/package-check.ts
  src/services/api/handlers/package-actions/services/mako-write-service.ts
  src/services/api/handlers/package-actions/services/package-action-write-service.ts
  src/services/data/handlers/sinkMain.ts
  src/services/ui/src/components/Cards/OptionCard.tsx
  src/services/ui/src/features/dashboard/Lists/renderCells/index.tsx
  src/services/ui/src/features/package-actions/ActionForm.tsx
  src/services/ui/src/features/package-actions/ActionPage.tsx
  src/services/ui/src/features/package-actions/lib/index.ts
  src/services/ui/src/features/package-actions/lib/modules/temporary-extension/legacy-page.tsx
  src/services/ui/src/features/package-actions/lib/modules/update-id/index.tsx
  src/services/ui/src/features/package/package-actions/index.tsx
  src/services/ui/src/features/submission/app-k/index.tsx
  src/services/ui/src/features/submission/spa/chip-intitial.tsx
  src/services/ui/src/features/submission/spa/medicaid-initial.tsx
  src/services/ui/src/features/submission/waiver/capitated/capitated-1915-b-waiver-amendment.tsx
  src/services/ui/src/features/submission/waiver/capitated/capitated-1915-b-waiver-initial.tsx
  src/services/ui/src/features/submission/waiver/capitated/capitated-1915-b-waiver-renewal.tsx
  src/services/ui/src/features/submission/waiver/contracting/contracting-1915-b-waiver-amendment.tsx
  src/services/ui/src/features/submission/waiver/contracting/contracting-1915-b-waiver-initial.tsx
  src/services/ui/src/features/submission/waiver/contracting/contracting-1915-b-waiver-renewal.tsx
  src/services/ui/src/features/submission/waiver/shared-components/SubmitAndCancelBtnSection.tsx
  src/services/ui/src/hooks/index.ts
  src/services/ui/src/hooks/useQuery.ts
  src/services/ui/src/utils/formOrigin.ts
  src/services/ui/src/utils/stripQueryString.ts
Labels: type: FIX, type: REFACTOR, status: READY

#655 feat(g2b): Add G2b to webforms list
  src/services/api/webforms/G2B/index.ts
  src/services/api/webforms/G2B/v202401.ts
  src/services/api/webforms/index.ts
  src/services/ui/e2e/tests/a11y/index.spec.ts
Labels: type: FEAT, status: READY

#691 feat(dep-wrapper-update): update depdency wrapper logic and testing
  lib/packages/shared-types/forms.ts
  react-app/src/components/RHF/SlotField.tsx
  react-app/src/components/RHF/dependencyWrapper.tsx
  react-app/src/components/RHF/tests/depedencyWrapper.test.tsx
Labels: type: FEAT, status: READY
