Repository Enterprise-CMCS/macpro-mako, pull requests merged in 2024-02, with the labels that each got.

#354 fix(versioning): add year format for form version
  src/services/api/layers/ABP1/v202401.ts
  src/services/api/layers/ABP1/v202402.ts
  src/services/api/layers/ABP10/v202401.ts
  src/services/api/layers/ABP3/v202401.ts
  src/services/api/layers/ABP3_1/v202401.ts
  src/services/ui/src/components/Webform/index.tsx
Labels: type: FIX, status: READY

#366 feat(alerts): Modal and Alert banner upgrades
  docs/docs/team-norms/code-style.md
  src/services/ui/src/components/Alert/index.tsx
  src/services/ui/src/components/Cards/OptionCard.tsx
  src/services/ui/src/components/Context/alertContext.test.tsx
  src/services/ui/src/components/Context/alertContext.tsx
  src/services/ui/src/components/Context/modalContext.test.tsx
  src/services/ui/src/components/Context/modalContext.tsx
  src/services/ui/src/components/Layout/index.tsx
  src/services/ui/src/hooks/useActionFormController.ts
  src/services/ui/src/pages/actions/IssueRai.tsx
  src/services/ui/src/pages/actions/RespondToRai.tsx
  src/services/ui/src/pages/actions/ToggleRaiResponseWithdraw.tsx
  src/services/ui/src/pages/actions/WithdrawPackage.tsx
  src/services/ui/src/pages/actions/WithdrawRai.tsx
  src/services/ui/src/pages/actions/index.tsx
  src/services/ui/src/pages/actions/template.tsx
  src/services/ui/src/pages/dashboard/Lists/renderCells/index.tsx
  src/services/ui/src/pages/detail/index.tsx
  src/services/ui/src/pages/form/chip-form.tsx
  src/services/ui/src/pages/form/medicaid-form.tsx
  src/services/ui/src/pages/form/modals.tsx
  src/services/ui/src/pages/form/waiver/capitated/capitated-1915-b-waiver-amendment.tsx
  src/services/ui/src/pages/form/waiver/capitated/capitated-1915-b-waiver-initial.tsx
  src/services/ui/src/pages/form/waiver/capitated/capitated-1915-b-waiver-renewal.tsx
  src/services/ui/src/pages/form/waiver/contracting/contracting-1915-b-waiver-amendment.tsx
  src/services/ui/src/pages/form/waiver/contracting/contracting-1915-b-waiver-initial.tsx
  src/services/ui/src/pages/form/waiver/contracting/contracting-1915-b-waiver-renewal.tsx
  src/services/ui/src/utils/formOrigin.ts
Labels: type: FEAT, status: READY

#381 fix(uploads): Fix file upload async cutoff
  src/services/ui/src/api/submissionService.ts
Labels: type: FIX, status: READY

#378 fix(testing): Clean up test runner implementations
  package.json
  src/libs/package.json
  src/libs/tests/env.test.ts
  src/packages/shared-types/package.json
  src/packages/shared-types/tsconfig.json
  src/packages/shared-utils/package.json
  src/packages/shared-utils/regex.test.ts
  src/packages/shared-utils/tests/regex.test.ts
  src/services/api/handlers/forms.ts
  src/services/api/handlers/tests/forms.test.ts
  src/services/api/package.json
  src/services/ui/package.json
  src/services/ui/src/components/Cards/OptionCard.test.tsx
  src/services/ui/src/components/Cards/index.ts
  src/services/ui/testing/setup.ts
  src/tests/vitest.config.ts
  turbo.json
  yarn.lock
Labels: type: FIX, status: NOT READY

#360 feat(webform): new ABP11 form and updated Upload component
  src/packages/shared-types/forms.ts
  src/services/api/webforms/ABP11/index.ts
  src/services/api/webforms/ABP11/v202401.ts
  src/services/api/webforms/index.ts
  src/services/ui/src/components/Inputs/upload.tsx
  src/services/ui/src/components/RHF/Document.tsx
  src/services/ui/src/components/RHF/Slot.tsx
  src/services/ui/src/components/RHF/utils/initializer.ts
  src/services/ui/src/components/Webform/index.tsx
  src/services/ui/src/pages/actions/renderSlots.tsx
  src/services/ui/src/pages/form/chip-form.tsx
  src/services/ui/src/pages/form/medicaid-form.tsx
  src/services/ui/src/pages/form/waiver/capitated/capitated-1915-b-waiver-amendment.tsx
  src/services/ui/src/pages/form/waiver/capitated/capitated-1915-b-waiver-initial.tsx
  src/services/ui/src/pages/form/waiver/capitated/capitated-1915-b-waiver-renewal.tsx
  src/services/ui/src/pages/form/waiver/contracting/contracting-1915-b-waiver-amendment.tsx
  src/services/ui/src/pages/form/waiver/contracting/contracting-1915-b-waiver-initial.tsx
  src/services/ui/src/pages/form/waiver/contracting/contracting-1915-b-waiver-renewal.tsx
Labels: type: FEAT, status: TESTING

#406 feat(OY2-26213): APP-K
  src/packages/shared-types/action-types/index.ts
  src/packages/shared-types/action-types/new-submission.ts
  src/packages/shared-types/action-types/remove-appk-child.ts
  src/packages/shared-types/actions.ts
  src/packages/shared-types/opensearch/changelog/index.ts
  src/packages/shared-types/opensearch/main/transforms/index.ts
  src/packages/shared-types/opensearch/main/transforms/new-submission.ts
  src/packages/shared-types/opensearch/main/transforms/remove-appk-child.ts
  src/packages/shared-utils/package-actions/rules.ts
  src/services/api/handlers/action.ts
  src/services/api/handlers/appkNewSubmission.ts
  src/services/api/handlers/packageActions.ts
  src/services/api/handlers/submit.ts
  src/services/api/repack/repack.ts
  src/services/api/repack/tsconfig.json
  src/services/api/repack/types.d.ts
  src/services/api/serverless.yml
  src/services/data/handlers/sinkOnemac.ts
  src/services/ui/src/api/submissionService.ts
  src/services/ui/src/components/Opensearch/main/useOpensearch.ts
  src/services/ui/src/components/Opensearch/utils.ts
  src/services/ui/src/components/PackageDetails/DetailItemsGrid.tsx
  src/services/ui/src/components/PackageDetails/ReviewTeamList.tsx
  src/services/ui/src/components/PackageDetails/index.ts
  src/services/ui/src/components/Routing/routes.ts
  src/services/ui/src/components/index.tsx
  src/services/ui/src/lib/common-types.ts
  src/services/ui/src/pages/create/options.tsx
  src/services/ui/src/pages/dashboard/index.tsx
  src/services/ui/src/pages/detail/index.tsx
  src/services/ui/src/pages/detail/package-activity/hook.ts
  src/services/ui/src/pages/detail/package-activity/index.tsx
  src/services/ui/src/pages/detail/package-details/appk.tsx
  src/services/ui/src/pages/detail/package-details/hooks.tsx
  src/services/ui/src/pages/detail/package-details/index.tsx
  src/services/ui/src/pages/form/app-k/DragNDrop.tsx
  src/services/ui/src/pages/form/app-k/consts.ts
  src/services/ui/src/pages/form/app-k/index.tsx
  src/services/ui/src/pages/form/app-k/slots.tsx
  src/services/ui/src/pages/form/chip-form.tsx
  src/services/ui/src/pages/form/form-breadcrumbs.ts
  src/services/ui/src/pages/form/index.tsx
  src/services/ui/src/pages/form/medicaid-form.tsx
  src/services/ui/src/router.tsx
  src/services/ui/src/utils/labelMappers.ts
Labels: type: FEAT, status: READY

#411 Fix(OY2-26213): add remove-appk-child oneMac sink logic
  src/services/data/handlers/sinkChangelog.ts
  src/services/data/handlers/sinkMain.ts
Labels: type: FIX, status: READY

#383 feat(launchDarkly): add Launch Darkly to our MAKO environment
  docs/docs/developer-guide/launch-darkly.md
  src/packages/shared-types/index.ts
  src/packages/shared-utils/feature-flags.ts
  src/packages/shared-utils/index.ts
  src/services/api/package.json
  src/services/api/serverless.yml
  src/services/ui/e2e/pages/loginPage.ts
  src/services/ui/e2e/tests/a11y/index.spec.ts
  src/services/ui/package.json
  src/services/ui/serverless.yml
  src/services/ui/src/components/MaintenanceBanner/index.tsx
  src/services/ui/src/components/Webform/index.tsx
  src/services/ui/src/components/index.tsx
  src/services/ui/src/config.tsx
  src/services/ui/src/main.tsx
  yarn.lock
Labels: type: FEAT, status: READY

#413 fix(OY2-25329): fine-tune dashboard search query
  src/services/ui/src/components/Opensearch/utils.ts
Labels: type: FIX, status: READY

#392 feat(waiver action support): Add post-initial-submission waiver actions to the application
  package.json
  src/packages/shared-types/action-types/withdraw-package.ts
  src/packages/shared-types/attachments.ts
  src/packages/shared-types/tests/seatool.test.ts
  src/packages/shared-utils/feature-flags.ts
  src/services/api/handlers/packageActions.ts
  src/services/ui/package.json
  src/services/ui/src/api/submissionService.ts
  src/services/ui/src/components/Context/index.ts
  src/services/ui/src/components/Inputs/upload.tsx
  src/services/ui/src/components/RHF/Slot.tsx
  src/services/ui/src/components/Routing/routes.ts
  src/services/ui/src/components/Routing/types.ts
  src/services/ui/src/features/actions/WithdrawPackage.tsx
  src/services/ui/src/features/actions/renderSlots.tsx
  src/services/ui/src/features/dashboard/Lists/renderCells/index.tsx
  src/services/ui/src/features/package-actions/ActionWrapper.tsx
  src/services/ui/src/features/package-actions/IssueRai.tsx
  src/services/ui/src/features/package-actions/RespondToRai.tsx
  src/services/ui/src/features/package-actions/ToggleRaiResponseWithdraw.tsx
  src/services/ui/src/features/package-actions/WithdrawPackage.tsx
  src/services/ui/src/features/package-actions/WithdrawRai.tsx
  src/services/ui/src/features/package-actions/index.tsx
  src/services/ui/src/features/package-actions/shared-components.tsx
  src/services/ui/src/features/package/index.tsx
  src/services/ui/src/features/submission/spa/chip-intitial.tsx
  src/services/ui/src/features/submission/spa/medicaid-initial.tsx
  src/services/ui/src/features/submission/waiver/capitated/capitated-1915-b-waiver-amendment.tsx
  src/services/ui/src/features/submission/waiver/capitated/capitated-1915-b-waiver-initial.tsx
  src/services/ui/src/features/submission/waiver/capitated/capitated-1915-b-waiver-renewal.tsx
  src/services/ui/src/features/submission/waiver/contracting/contracting-1915-b-waiver-amendment.tsx
  src/services/ui/src/features/submission/waiver/contracting/contracting-1915-b-waiver-initial.tsx
  src/services/ui/src/features/submission/waiver/contracting/contracting-1915-b-waiver-renewal.tsx
  src/services/ui/src/router.tsx
  yarn.lock
Labels: type: FEAT, status: READY, status: TESTING
