Repository Enterprise-CMCS/macpro-mako, pull requests merged in 2024-06, with the labels that each got.

#564 fix(package-actions): Remove package actions API fetching
  src/packages/shared-utils/package-actions/getAvailableActions.ts
  src/packages/shared-utils/package-actions/rules.ts
  src/packages/shared-utils/package-check.ts
  src/packages/shared-utils/tests/getAvailableActions.test.ts
  src/packages/shared-utils/tests/testData.ts
  src/services/ui/src/api/useSearch.ts
  src/services/ui/src/features/package/index.tsx
  src/services/ui/src/features/package/package-actions/index.tsx
Labels: type: FIX, type: REFACTOR, status: READY

#547 fix(forms): Make form UI cohesive
  src/services/ui/src/components/Cards/SectionCard.tsx
  src/services/ui/src/components/DetailsSection/index.tsx
  src/services/ui/src/components/Form/content/ContentWrappers.tsx
  src/services/ui/src/components/Form/fields/AdditionalInfoSection.tsx
  src/services/ui/src/components/Form/fields/AttachmentsSection.tsx
  src/services/ui/src/components/Form/fields/FormButtons.tsx
  src/services/ui/src/components/Form/fields/index.ts
  src/services/ui/src/components/Form/old-content.tsx
  src/services/ui/src/features/package-actions/ActionForm.tsx
  src/services/ui/src/features/package-actions/lib/contentSwitch.ts
  src/services/ui/src/features/package-actions/lib/modules/complete-intake/index.tsx
  src/services/ui/src/features/package-actions/lib/modules/issue-rai/index.tsx
  src/services/ui/src/features/package-actions/lib/modules/respond-to-rai/spa/chip-rai.tsx
  src/services/ui/src/features/package-actions/lib/modules/respond-to-rai/spa/med-rai.tsx
  src/services/ui/src/features/package-actions/lib/modules/respond-to-rai/waiver/b-waiver-rai.tsx
  src/services/ui/src/features/package-actions/lib/modules/temporary-extension/index.tsx
  src/services/ui/src/features/package-actions/lib/modules/temporary-extension/legacy-page.tsx
  src/services/ui/src/features/package-actions/lib/modules/toggle-rai-withdraw/index.tsx
  src/services/ui/src/features/package-actions/lib/modules/update-id/index.tsx
  src/services/ui/src/features/package-actions/lib/modules/withdraw-package/index.tsx
  src/services/ui/src/features/package-actions/lib/modules/withdraw-package/spa/withdraw-chip-rai.tsx
  src/services/ui/src/features/package-actions/lib/modules/withdraw-rai/index.tsx
  src/services/ui/src/features/package/admin-changes/index.tsx
  src/services/ui/src/features/submission/app-k/index.tsx
  src/services/ui/src/features/submission/spa/chip-intitial.tsx
  src/services/ui/src/features/submission/spa/medicaid-initial.tsx
  src/services/ui/src/features/submission/waiver/capitated/capitated-1915-b-waiver-amendment.tsx
  src/services/ui/src/features/submission/waiver/capitated/capitated-1915-b-waiver-initial.tsx
  src/services/ui/src/features/submission/waiver/contracting/contracting-1915-b-waiver-amendment.tsx
  src/services/ui/src/features/submission/waiver/contracting/contracting-1915-b-waiver-initial.tsx
  src/services/ui/src/features/submission/waiver/contracting/contracting-1915-b-waiver-renewal.tsx
  src/services/ui/src/features/submission/waiver/shared-components/SubmitAndCancelBtnSection.tsx
  src/services/ui/src/index.css
  src/services/ui/tailwind.config.js
Labels: type: FIX, status: TESTING

#574 feat(webform-gen): generate names from form data
  src/packages/shared-types/forms.ts
  src/services/api/webforms/ABP1/v202401.ts
  src/services/api/webforms/ABP1/v202402.ts
  src/services/api/webforms/ABP10/v202401.ts
  src/services/api/webforms/ABP11/v202401.ts
  src/services/api/webforms/ABP2A/v202401.ts
  src/services/api/webforms/ABP2B/v202401.ts
  src/services/api/webforms/ABP2C/v202401.ts
  src/services/api/webforms/ABP3/v202401.ts
  src/services/api/webforms/ABP3_1/v202401.ts
  src/services/api/webforms/ABP4/v202401.ts
  src/services/api/webforms/ABP5/v202401.ts
  src/services/api/webforms/ABP6/v202401.ts
  src/services/api/webforms/ABP7/v202401.ts
  src/services/api/webforms/ABP9/v202401.ts
  src/services/ui/src/components/Inputs/form.tsx
  src/services/ui/src/components/RHF/Document.tsx
  src/services/ui/src/components/RHF/FieldArray.tsx
  src/services/ui/src/components/RHF/FieldGroup.tsx
  src/services/ui/src/components/RHF/FormGroup.tsx
  src/services/ui/src/components/RHF/Section.tsx
  src/services/ui/src/components/RHF/Slot.tsx
  src/services/ui/src/components/RHF/SlotField.tsx
  src/services/ui/src/components/RHF/tests/NameGen.test.tsx
  src/services/ui/src/components/RHF/tests/Slot.test.tsx
  src/services/ui/src/components/RHF/tests/SlotField.test.tsx
  src/services/ui/src/components/RHF/utils/initializer.ts
Labels: type: FEAT, status: READY

#559 fix(filter): filter ranges changes when closing and opening the filter side bar
  src/services/ui/src/components/Opensearch/main/Filtering/Drawer/Filterable/DateRange.tsx
Labels: In Testing, priority: MED, type: FIX, status: READY

#581 fix(add abp2a fixes):Add abp2a webform changes requested from HCD
  src/services/api/webforms/ABP2A/v202401.ts
  src/services/ui/src/components/Inputs/textarea.tsx
  src/services/ui/src/components/Inputs/upload.tsx
  src/services/ui/src/components/RHF/Section.tsx
Labels: In Testing

#582 fix(abp2b hcd): Ab2b fixes requested by HCD
  src/services/api/webforms/ABP2B/v202401.ts
Labels: status: TESTING

#578 fix(OY2-27785): remove dashboard search whitespace
  src/services/ui/src/components/SearchForm/index.tsx
Labels: priority: LOW, type: FIX, status: READY

#593 fix(OY2-28003): package ID text wrap + responsiveness
  src/services/ui/src/components/BreadCrumb/BreadCrumb.tsx
  src/services/ui/src/features/package/index.tsx
Labels: type: FIX, status: READY

#608 feat(UI): Add Appendix K to Withdraw Package Title
  src/services/ui/src/features/package-actions/lib/modules/withdraw-package/index.tsx
Labels: good first issue, type: FIX, type: CHORE

#600 fix(email): Files section in Submission emails for all package types shows wrong file name type
  src/services/email/handlers/processEmails.tsx
  src/services/email/libs/data-lib.js
Labels: priority: MED, type: FIX, status: READY
