Repository Enterprise-CMCS/macpro-mako, pull requests merged in 2025-02, with the labels that each got.

#1106 fix(all-state-emails): Add logic to include all state emails in templates
  lib/libs/email/content/withdrawPackage/index.tsx
Labels: type: FIX

#1118 fix(correct withdraw templates): Add logic to fix withdraw email logic for both request and confirmation
  lib/lambda/processEmailsHandler.test.ts
  lib/libs/email/content/email-components.tsx
  lib/libs/email/content/withdrawConfirmation/emailTemplates/WaiverState.tsx
  lib/libs/email/content/withdrawConfirmation/index.tsx
  lib/libs/email/content/withdrawPackage/emailTemplates/WaiverState.tsx
  lib/libs/email/content/withdrawPackage/index.tsx
  lib/libs/email/index.ts
  lib/libs/email/preview/WithdrawConfirmation/State/__snapshots__/WithdrawConfirmationState.test.tsx.snap
  lib/libs/email/preview/WithdrawPackage/State/__snapshots__/WithdrawPackageState.test.tsx.snap
Labels: type: FIX, status: READY

#1135 fix(withdraw-email): fix spelling on subject line
  lib/libs/email/content/withdrawPackage/index.tsx
Labels: type: FIX, status: READY

#1180 Temp-main dev branch
  lib/lambda/getPackageActions.test.ts
  lib/lambda/search.test.ts
  lib/packages/shared-types/actions.ts
  lib/packages/shared-utils/package-actions/getAvailableActions.test.ts
  lib/packages/shared-utils/package-actions/getAvailableActions.ts
  mocks/data/items.ts
Labels: type: CHORE

#1172 feat(OS filter saved state): add logic to store filters and sorting for opensearch into local state
  react-app/src/components/Opensearch/main/Table/index.tsx
  react-app/src/components/Opensearch/main/index.test.tsx
  react-app/src/components/Opensearch/main/index.tsx
  react-app/src/features/dashboard/index.tsx
  react-app/src/hooks/useLocalStorage.test.tsx
  react-app/src/hooks/useLocalStorage.ts
Labels: type: FEAT
